<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180703/1-1PF3110T2.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/180703/1-1PF3110T2.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="7360";
$z[1][4]['height']="4912";
$z[2]=Array("img"," /uploads/allimg/180703/1-1PF3110T6.jpg ",238,381);
$z[2][4]['ddimg']="/uploads/allimg/180703/1-1PF3110T6.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="7360";
$z[2][4]['height']="4912";
$z[3]=Array("img"," /uploads/allimg/180703/1-1PF3110T9.jpg ",383,526);
$z[3][4]['ddimg']="/uploads/allimg/180703/1-1PF3110T9.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="7360";
$z[3][4]['height']="4912";
$z[4]=Array("img"," /uploads/allimg/180703/1-1PF3110U2.jpg ",528,671);
$z[4][4]['ddimg']="/uploads/allimg/180703/1-1PF3110U2.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="7360";
$z[4][4]['height']="4912";
$z[5]=Array("img"," /uploads/allimg/180703/1-1PF3110U5.jpg ",673,816);
$z[5][4]['ddimg']="/uploads/allimg/180703/1-1PF3110U5.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="7360";
$z[5][4]['height']="4912";

?>