<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180703/1-1PF3160232.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/180703/1-1PF3160232.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="7360";
$z[1][4]['height']="4912";
$z[2]=Array("img"," /uploads/allimg/180703/1-1PF3160234.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/180703/1-1PF3160234.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="7360";
$z[2][4]['height']="4912";
$z[3]=Array("img"," /uploads/allimg/180703/1-1PF3160236.jpg ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/180703/1-1PF3160236.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="7360";
$z[3][4]['height']="4912";
$z[4]=Array("img"," /uploads/allimg/180703/1-1PF3160238.jpg ",534,679);
$z[4][4]['ddimg']="/uploads/allimg/180703/1-1PF3160238.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="7360";
$z[4][4]['height']="4912";
$z[5]=Array("img"," /uploads/allimg/180703/1-1PF3160240.jpg ",681,826);
$z[5][4]['ddimg']="/uploads/allimg/180703/1-1PF3160240.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="7360";
$z[5][4]['height']="4912";

?>